voting-app:
  build: ./voting-app/.
  links:
    - "redis:redis"
  ports:
    - "5000:80"
result-app:
  build: ./result-app/.
  links:
    - "redis:redis"
  ports:
    - "5002:80"
    - "5001:8080"
redis:
  image: tutum/redis
  environment:
    - REDIS_PASS=password
